Круковский Сергей
TOPans/andersen-js-course pull request #1
Opened 2019-06-05 22:09 UTC by TOPans

2019-06-08 09:47 UTC, volvachev requested changes

2019-06-08 09:47 UTC, volvachev commented on src/array-practice/task1.js
> +  return callbackFun == undefined
Не используй ==.
Замени тернарник на параметр по умолчанию в функции.

2019-06-08 09:47 UTC, volvachev commented on src/array-practice/task2.js
> +    .filter(item => secondArray.indexOf(item) == -1)
не используй ==
замени indexOf на метод из es6.

2019-06-08 09:47 UTC, volvachev commented on src/array-practice/task3.js
> +  inputArray.reverse().forEach(val);
reverse мутирует исходный массив, используй reverse на новом массиве.

2019-06-08 09:47 UTC, volvachev commented on src/array-practice/task4.js
> +  return firstArray.concat(secondArray).filter((item, index, arr) => arr.indexOf(item) == index);
Воспользуйся новой структурой данных из es6.

2019-06-08 09:47 UTC, volvachev commented on src/array-practice/task5.js
> +    next: (fun = () => {
что за переменная fun.
просто сделай метод.
возвращай из функции результат.

2019-06-08 09:47 UTC, volvachev commented on src/array-practice/task8.js
> +  return inputArray.filter(elem => inputArrayArgs.indexOf(elem) == -1);
не используй ==
замени на метод из es6.

2019-06-08 09:47 UTC, volvachev commented on src/array-practice/task9.js
> +    .map((curValue, index) => (curValue === value ? index : -1))
Есть более подходящий метод массива для этого.

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task10.js
> +    return super.getName() + " " + text;
template string. (es6)

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task4.js
> +  foo = () => "test";
почему создаешь в глобальную область видимости эту функцию?
воспользуйся (const, let)

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task4.js
> +    bar: (bar = () => x + y),
не надо создавать глобальную переменную bar.
Воспользуйся es6, сокращенной записью метода. (и внутри использовался this)

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task4.js
> +    ["baz" + foo()]: "new feild"
template string.(es6)

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task5.js
> +  return [name, val, objName, objValue]=[array[0], array[1], obj.name, obj.val]
Воспользуйся деструктуризацией аргументов.

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task6.js
> +  var {
пишим на es6(var не используй)

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task6.js
> +    isActive: isActive = isActive === undefined ? false : isActive,
воспользуйся параметром по умолчанию для деструктуризации.

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task9.js
> +    "test".indexOf("est") !== -1,
воспользуйся методами из es6.

2019-06-08 09:47 UTC, volvachev commented on src/es-features/task8.js
> +      return (this.fives = this.nums.filter(item => item % 5 === 0));
Не возвращай результат присвоения, напиши раздельно

2019-06-09 11:41 UTC, TOPans commented on src/array-practice/task1.js
> +  return callbackFun == undefined
Исправил

2019-06-09 11:41 UTC, TOPans commented on src/array-practice/task2.js
> +    .filter(item => secondArray.indexOf(item) == -1)
Исправил

2019-06-09 11:41 UTC, TOPans commented on src/array-practice/task3.js
> +  inputArray.reverse().forEach(val);
Исправил

2019-06-09 11:41 UTC, TOPans commented on src/array-practice/task4.js
> +  return firstArray.concat(secondArray).filter((item, index, arr) => arr.indexOf(item) == index);
Исправил

2019-06-09 11:41 UTC, TOPans commented on src/array-practice/task5.js
> +    next: (fun = () => {
Исправил

2019-06-09 11:41 UTC, TOPans commented on src/array-practice/task8.js
> +  return inputArray.filter(elem => inputArrayArgs.indexOf(elem) == -1);
Исправил

2019-06-09 11:41 UTC, TOPans commented on src/array-practice/task9.js
> +    .map((curValue, index) => (curValue === value ? index : -1))
Исправил

2019-06-09 11:41 UTC, TOPans commented on src/es-features/task10.js
> +    return super.getName() + " " + text;
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task4.js
> +  foo = () => "test";
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task4.js
> +    bar: (bar = () => x + y),
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task4.js
> +    ["baz" + foo()]: "new feild"
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task5.js
> +  return [name, val, objName, objValue]=[array[0], array[1], obj.name, obj.val]
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task6.js
> +  var {
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task6.js
> +    isActive: isActive = isActive === undefined ? false : isActive,
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task9.js
> +    "test".indexOf("est") !== -1,
Исправил

2019-06-09 11:42 UTC, TOPans commented on src/es-features/task8.js
> +      return (this.fives = this.nums.filter(item => item % 5 === 0));
Исправил

2019-06-09 14:11 UTC, volvachev requested changes

2019-06-09 14:11 UTC, volvachev commented on src/array-practice/task3.js
> +  let reverseArray = []
```
inputArray.slice().reverse().forEach(val);
```

2019-06-09 14:11 UTC, volvachev commented on src/array-practice/task5.js
> +      console.log(
Возвращай из функции результат.

2019-06-09 14:11 UTC, volvachev commented on src/array-practice/task9.js
> +      arrayIndexes.push(index);
Не так воспользовался reduce
у тебя есть первый аргумент используй его вместо arrayIndexes;

2019-06-09 15:12 UTC, TOPans commented on src/array-practice/task3.js
> +  let reverseArray = []
Исправил

2019-06-09 15:12 UTC, TOPans commented on src/array-practice/task5.js
> +      console.log(
Исправил

2019-06-09 15:12 UTC, TOPans commented on src/array-practice/task9.js
> +      arrayIndexes.push(index);
Исправил

2019-06-10 07:47 UTC, merged